name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://qxq.moe
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up scripts
        working-directory: scripts/
        run: npm install

      - name: Run build scripts
        run: node scripts/copy.js && node scripts/font.js && node scripts/thumbnail.js

      - name: Deploy to production server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "dist/"
          target: ${{ secrets.TARGET_PATH }}
          strip_components: 1
